spring:
  datasource:
    url: "jdbc:mysql://192.168.1.13:3306/dj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "admin"
    password: "milowang2020"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: "cn.milolab.dj.bean.entity"

shiro:
  enabled: true

miniprogram:
  appid: ""
  appsecret: ""

logging:
  level:
    cn:
      milolab:
        dj: debug
